### PR TITLE
fix: saveItem

### PR DESCRIPTION
**Pull request by dpaez**
This PR is an attempt to improve a possible scenario where we store in the localdb a mismatch between `version` and `lastModified` values. i.e.: version is bigger than other module but the lastModified is older. Both values should go bigger with time.

This could help prevent things like #220

### CODE REVIEW

**Comment by jameslibscie** [comment]
@juliangruber Could you perhaps test whether this solves the problem?

**Review by juliangruber — CHANGES_REQUESTED** [review]
The same issue unfortunately

image

image

**Comment by dpaez** [comment]
@juliangruber and @jameslibscie I've updated the `list content` test with some `set` operations in between and more comparisons. 

Is this similar to the behaviour that ends with the bug?

**Comment by juliangruber** [comment]
The steps in Hypergraph are

1) Create profile
2) Create content
3) Register content
4) _Restart the app_
5) List contents

**Comment by dpaez** [comment]
Thanks @juliangruber this is super helpful

**Comment by juliangruber** [comment]
Sorry for not providing these steps earlier 😅

**Comment by dpaez** [comment]
Added a new test that follows the steps that @juliangruber described before. It's passing so maybe this is an indication that the issue is somewhere? Do we have any other info to add here?

**Comment by juliangruber** [comment]
> Added a new test that follows the steps that @juliangruber described before. It's passing so maybe this is an indication that the issue is somewhere? Do we have any other info to add here?

No other info besides using the steps above you should be able to reproduce this in Hypergraph Desktop:

1) Reset DB
1) Create profile
1) Create registered module
1) Restart app
1) Open drafts -> you see the registered module
1) Navigate somewhere else
1) Open drafts -> you don't see the registered module

I looked at the implementation of `listContents` and saw that it just returns the DB items. That makes me wonder how after launching Hypergraph, where we _don't_ write anything to the DB, only read, the returned values could be different.

Is there maybe something happening in `this.ready()` that modifies the DB items?

**Comment by juliangruber** [comment]
> Yes. On `ready` we call the `refreshMTimes` that is used to check if something changed while the sdk was offline. This function can update the localdb if that happens.

Thanks, I'm about to try out these new changes. I still have no clue why during or right after `refreshMTimes` the version would be higher than afterwards though

**Review by juliangruber — APPROVED** [review]
This seems to have fixed it Diego :O <3

I can't reproduce any more :)

**Review by jameslibscie — APPROVED** [review]
All good!

**Comment by dpaez** [comment]
Glad it worked. I think that we can go with this fix for now. I'd like to recheck the `refreshMTimes` function soon.

**Pull request merged**
