### PR TITLE
Update: hypercore-crypto

### PR DESCRIPTION
**Pull request by dpaez**
Related to #165

### CODE REVIEW

**Comment by dpaez** [comment]
> Has this package-lock been manually changed or is it `rm package-lock.json && npm install`?

Was `rm package-lock.json && npm install`

Now, I've updated the hypercore-crypto dep, to version 2.

**Comment by juliangruber** [comment]
I think this still contains the pre-v3 sodium native, if you look at the package-lock. `npm ls sodium-native` should tell what brings it in (if I'm not mistaken)

**Comment by dpaez** [comment]
yeah, `universal-dat-storage` includes this dep :( I can see if I can remove it now. FWIW this dep is no longer used in the latest version of the SDK (hyperdrive-daemon based)

**Comment by dpaez** [comment]
Cool, I've managed to remove the universal-dat-storage dep, so now we are only using sodium-native@3

**Pull request merged**
