### PR TITLE
Fix: number version metadata

### PR DESCRIPTION
**Pull request by dpaez**
Always cast version to Number

### CODE REVIEW

**Comment by dpaez** [comment]
i try to write some tests, but now we are forcing version to be Numbers all the time, so I'm finding difficult to pass a string and get an error, even try to work with `saveItem` method directly

**Comment by juliangruber** [comment]
> but now we are forcing version to be Numbers all the time, so I'm finding difficult to pass a string and get an error

You could revert the fix, then add tests, then commit the fix

**Comment by dpaez** [comment]
Added new test, that is throwing with invalid metadata. Next going to re-apply previous fix.

**Comment by dpaez** [comment]
...And we are good to go now, adding those fixes remind of this classic scene 😅 https://www.youtube.com/watch?v=AbSehcT19u0

**Comment by juliangruber** [comment]
> ...And we are good to go now, adding those fixes remind of this classic scene 😅 https://www.youtube.com/watch?v=AbSehcT19u0

Hahahah a classic! :D

**Pull request merged**
